export const DEFAULT_PERMISSIONS: Record<string, Record<string, 'none' | 'read' | 'write' | 'full'>> = {
  admin: {
    crm:           'full',
    tareas:        'full',
    notas:         'full',
    propiedades:   'full',
    proyectos:     'full',
    ventas:        'full',
    simulador:     'full',
    flip:          'full',
    presupuestos:  'full',
    reportes:      'full',
    marketing:     'full',
    configuracion: 'full',
  },
  agente: {
    crm:           'read',
    tareas:        'full',
    notas:         'full',
    propiedades:   'write',
    proyectos:     'write',
    ventas:        'none',
    simulador:     'none',
    flip:          'none',
    presupuestos:  'none',
    reportes:      'full',
    marketing:     'none',
    configuracion: 'none',
  },
  cm: {
    crm:           'none',
    tareas:        'write',
    notas:         'write',
    propiedades:   'write',
    proyectos:     'write',
    ventas:        'none',
    simulador:     'none',
    flip:          'none',
    presupuestos:  'none',
    reportes:      'none',
    marketing:     'write',
    configuracion: 'none',
  },
  finanzas: {
    crm:           'none',
    tareas:        'none',
    notas:         'none',
    propiedades:   'none',
    proyectos:     'none',
    ventas:        'full',
    simulador:     'full',
    flip:          'full',
    presupuestos:  'full',
    reportes:      'read',
    marketing:     'none',
    configuracion: 'none',
  },
  viewer: {
    crm:           'read',
    tareas:        'read',
    notas:         'read',
    propiedades:   'read',
    proyectos:     'read',
    ventas:        'none',
    simulador:     'none',
    flip:          'none',
    presupuestos:  'none',
    reportes:      'read',
    marketing:     'read',
    configuracion: 'none',
  },
};
