export const DEFAULT_PERMISSIONS: Record<string, Record<string, 'none' | 'read' | 'write' | 'full'>> = {
  admin: {
    crm: 'full',
    propiedades: 'full',
    proyectos: 'full',
    finanzas: 'full',
    marketing: 'full',
    tareas: 'full',
    notas: 'full',
    reportes: 'full',
    configuracion: 'full',
  },
  agente: {
    crm: 'read',
    propiedades: 'write',
    proyectos: 'write',
    finanzas: 'none',
    marketing: 'none',
    tareas: 'full',
    notas: 'full',
    reportes: 'full',
    configuracion: 'none',
  },
  cm: {
    crm: 'none',
    propiedades: 'write',
    proyectos: 'write',
    finanzas: 'none',
    marketing: 'write',
    tareas: 'write',
    notas: 'write',
    reportes: 'none',
    configuracion: 'none',
  },
  finanzas: {
    crm: 'none',
    propiedades: 'none',
    proyectos: 'none',
    finanzas: 'full',
    marketing: 'none',
    tareas: 'none',
    notas: 'none',
    reportes: 'read',
    configuracion: 'none',
  },
  viewer: {
    crm: 'read',
    propiedades: 'read',
    proyectos: 'read',
    finanzas: 'none',
    marketing: 'read',
    tareas: 'read',
    notas: 'read',
    reportes: 'read',
    configuracion: 'none',
  },
};
